# Generated by Django 4.2.1 on 2023-06-16 10:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_player_new_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('t_origin', models.IntegerField()),
                ('t_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
